spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/wallet
    username: wallet
    password: 123
    driver: org.postgresql.Driver
  liquibase:
    default-schema: wallet
    liquibase-schema: migration

authentication:
  valueOfJwtAccessSecretKey: Nb3YCWOp7kghAjoQkiNze2PTiLjQPQYdegcPM9oC77UkpUyJIuobhbeWRN+OI8PjXyGrITKxJWhYvrBlgH4JFA==
  valueOfJwtRefreshSecretKey: tSlh5T96KurUBOsKV0Ja/AIVGKpakIvDpejeRBxukbL9xJrQ1XoCodsoQhH6gmWiUevBe/Gw1FRiHn9HzExyCQ==
